### ISSUE TITLE
How did you train the network?

### ISSUE THREAD

**Issue by faruknane** [CaptainEven/FairMOTVehicle#10]
Hi, I'm really interested in fairmot work which is absolutely done perfectly. Could you please share a bit of the detail about how you trained the model for cars? Like did you freeze the body of the network and train only the heads? Did you train id head? How many images did you have for the training data? Did you encounter any generalization errors? I'll be so glad if you can answer my questions.

**Comment by CaptainEven** [comment]
Hi, thanks for interest. This repo is the extention work of FairMOT for one-class multi-object tracking, so the training details are almost the same as FairMOT except training dataset preparation. The content of training multi-vehicle using the DETRAC dataset is detailed in readme.
In the training phase, no layers of the model are fixed, i.e all parameters are tuned during training process. The details of DETRAC dataset can be found in their official website. As for the generalization erros, from my point of view, it's good.
If you are interested in multi-calss multi-object tracking as well, this is another extention work: 
https://github.com/CaptainEven/MCMOT

**Comment by faruknane** [comment]
@CaptainEven Thank you for the quick reply. I dig into MCMOT, there is a code below that draws gauss weight on the heatmap corresponding to that class id. I'm assuming, it writes 1 into some pixels that are close to the center of the object, right?
![image](https://user-images.githubusercontent.com/37745467/91637501-ac0b8080-ea11-11ea-8c3c-f596e5b89afc.png)

**Comment by CaptainEven** [comment]
Yes
