### ISSUE TITLE
Missing label.txt in DETRAC

### ISSUE THREAD

**Issue by YoushaaMurhij** [CaptainEven/FairMOTVehicle#6]
I am facing this error while attempting to train on DETRAC dataset:
```
(FairMOT)**********:~/FairMOT_ws/FairMOTVehicle/src$ python3 train.py --task mot --exp_id all_dla34 --gpus 0,1 --batch_size 8 --load_model '../models/all_dla34.pth' --data_cfg '../src/lib/cfg/detrac.json' --num_epochs 10 --lr 1e-5
Using tensorboardX
Fix size testing.
training chunk_sizes: [4, 4]
The output will be saved to  /home/*****/FairMOT_ws/FairMOTVehicle/src/lib/../../exp/mot/all_dla34
Setting up data...
Dataset root: /home/*****/FairMOT_ws/Datasets/
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    run(opt)
  File "train.py", line 48, in run
    transforms=transforms)
  File "/home/*****/FairMOT_ws/FairMOTVehicle/src/lib/datasets/dataset/jde.py", line 460, in __init__
    lb = np.loadtxt(lp)
  File "/home/*****/.conda/envs/FairMOT/lib/python3.7/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/*****/.conda/envs/FairMOT/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/*****/.conda/envs/FairMOT/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: /home/*****/FairMOT_ws/Datasets/DETRAC/labels_with_ids/train/MVI_39761/img1/img00542.txt not found.
 

```

**Comment by CaptainEven** [comment]
@YoushaaMurhij You may need to run preprocess and gen_labels first, then check 'OSError: /home/*****/FairMOT_ws/Datasets/DETRAC/labels_with_ids/train/MVI_39761/img1/img00542.txt not found.
 
' for corresponding label file(txt)'s existence.

**Comment by YoushaaMurhij** [comment]
I have already run gen_labels_detrac.py and generated all the .txt labels. but It seems that some .txt files are missing

**Comment by CaptainEven** [comment]
There are 3 functions need to be run in sequence: preprocess, gen_labels and gen_dot_train_file. Make sure the parameters(file/dir path..) are correct. May i see your print log in detail?

**Comment by YoushaaMurhij** [comment]
> There are 3 functions need to be run in sequence: preprocess, gen_labels and gen_dot_train_file, like:
> 
> ```
> preprocess(src_root='/mnt/diskb/even/Insight-MVT_Annotation_Train',
>            dst_root='/mnt/diskb/even/dataset/DETRAC')
> 
> gen_labels(xml_root='/mnt/diskb/even/DETRAC-Train-Annotations-XML',
>            img_root='/mnt/diskb/even/dataset/DETRAC/images/train',
>            label_root='/mnt/diskb/even/dataset/DETRAC/labels_with_ids/train',
>            viz_root='/mnt/diskb/even/viz_result')
> 
> gen_dot_train_file(data_root='/mnt/diskb/even/dataset',
>                    rel_path='/MCMOT/images',
>                    out_root='/mnt/diskb/even/MCMOT/src/data',
>                    f_name='mcmot.train')
> ```
> 
> Make sure the parameters(file/dir path..) are correct. May i see your print log in detail?

Thanks for your response. But, which logs you mean ?


`
if __name__ == '__main__':
    preprocess(src_root='/home/josh/Downloads/Insight-MVT_Annotation_Train',
               dst_root='/home/josh/FairMOT_ws/Datasets/DETRAC')

    gen_labels(xml_root='/home/josh/Downloads/DETRAC-Train-Annotations-XML',
               img_root='/home/josh/FairMOT_ws/Datasets/DETRAC/images/train',
               label_root='/home/josh/FairMOT_ws/Datasets/DETRAC/labels_with_ids/train',
               viz_root='/home/josh/FairMOT_ws/FairMOTVehicle/viz_result')

    gen_dot_train_file(data_root='/home/josh/FairMOT_ws/Datasets',
                       rel_path='/DETRAC/images/train',
                       out_root='/home/josh/FairMOT_ws/FairMOTVehicle/src/data')

    clean_train_set(img_root='/home/josh/FairMOT_ws/Datasets/DETRAC/images/train',
                    label_root='/home/josh/FairMOT_ws/Datasets/DETRAC/labels_with_ids/train')

    count_files(img_root='/home/josh/FairMOT_ws/Datasets/DETRAC/images/train',
                label_root='/home/josh/FairMOT_ws/Datasets/DETRAC/labels_with_ids')

    print('Done')

`

**Comment by CaptainEven** [comment]
The print log when run the gen script like:
![log](https://user-images.githubusercontent.com/9303747/88378468-a3e97100-cdd3-11ea-9c0b-538494749584.png)

**Comment by YoushaaMurhij** [comment]
Here is my log file and thanks again! 
https://drive.google.com/file/d/1-amJQf389EANaxPEouT856ueOOljn5Q3/view?usp=sharing

**Comment by CaptainEven** [comment]
@YoushaaMurhij Did u have made the json file 'detrac.json' in ./src/lib/cfg for detrac training?  My detrac.json is this:
{
    "root":"/mnt/diskb/even/dataset",
    "train":
    {
        "detrac":"./data/detrac.train"
    },
    "test_emb":
    {
        "detrac":"./data/detrac.train"
    },
    "test":
    {
        "detrac":"./data/detrac.train"
    }
}

After cfg file made, u need to set json file in opts.py like:
        self.parser.add_argument('--data_cfg', type=str,
                                 default='../src/lib/cfg/detrac.json',  # 'mot15.json',
                                 help='load data from cfg')
Finally, you can run under the src dir: python/python3 ./train.py

**Comment by CaptainEven** [comment]
It seems that your log file is ok, so i guess your err may be that u did not run the clean_train_set function(this function removes jpg file or txt label file if the counter part is missing in the train set). 
As i see in your log, you have run the 5 functions in sequence, nothing will be wrong now, check your cfg file and opts configuration, it will be ok. Wish good luck!

**Comment by YoushaaMurhij** [comment]
Everything looks Ok in my _.json_ file (I only changed the root). Anyway I tried the training file _train.py_ from the other repository MCMOT and it seems that no errors. 
Thanks for your help! I will write if everything goes well!

**Comment by linchunmian** [comment]
same error.@YoushaaMurhuk 
Could you have solved it?

**Comment by yuanliangxie** [comment]
I have solved the problem by using the `detrac.train` provied by the project instead of  generated by the `gen_labels_detrac.py`.
