### ISSUE TITLE
请问我这个训练的结果正常吗？

### ISSUE THREAD

**Issue by JunnYu** [CaptainEven/FairMOTVehicle#8]
![loss](https://user-images.githubusercontent.com/50394665/89510086-b7003600-d802-11ea-9488-287434544ec0.jpg)
我看loss都变成负数了

**Comment by CaptainEven** [comment]
正常，参考https://github.com/ifzhang/FairMOT/issues/38

**Comment by JunnYu** [comment]
> 正常，参考[ifzhang/FairMOT#38](https://github.com/ifzhang/FairMOT/issues/38)

好的，非常感谢！
